name: Build & Push Docker Image

on:
  push: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-demo:1.0.0-dev
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-demo:1.0.0-dev-${{ github.sha }}