name: Build & Push Docker Image

on:
  push: 
    branches: 
      - "main"
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Development
        if: github.ref == 'refs/heads/development'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-demo:1.1.0-dev
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-demo:1.1.0-dev-${{ github.sha }}

      - name: Build and Push Stable
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-demo:1.1.0
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-demo:1.1.0-${{ github.sha }}